language: python
python:
  - "3.5"
jobs:
  include:
    - stage:
      name: "Trigger rebuild of susi installer"
      jdk: oraclejdk8
      script: |
        echo "TRAVIS_BRANCH=$TRAVIS_BRANCH TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST"
        if [[ ($TRAVIS_PULL_REQUEST == false) ]] ; then
          sh .travis_scripts/trigger-travis.sh --branch development fossasia susi_installer $TRAVIS_ACCESS_TOKEN
        fi
    - stage: # runs in parallel with the previous job
      script: |
        pip install -U pytest-runner
        python setup.py pytest
